# Generated by Django 4.0.8 on 2023-01-01 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255, verbose_name='Name   اسم')),
                ('c_phone', models.CharField(max_length=13, verbose_name='Phone Number   رقم التليفون')),
                ('c_mail', models.CharField(max_length=100, verbose_name='Mail Address   عنوان البريد')),
                ('c_category', models.CharField(max_length=100, verbose_name='Category   فئة')),
                ('c_description', models.TextField(verbose_name='Description   وصف')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice_data',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=200, unique=True, verbose_name='Invoice Number   رقم الفاتورة')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('supply_date', models.DateTimeField(auto_now=True)),
                ('terms', models.CharField(max_length=200, verbose_name='Terms   مصطلحات')),
                ('sales_man', models.CharField(max_length=200, verbose_name='Sales Man   مندوب مبيعات')),
                ('customer_ref', models.CharField(max_length=200, verbose_name='Customer Reference   إشارة العملاء')),
                ('customer_id', models.CharField(max_length=100, verbose_name='Customer ID   هوية الزبون')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name   اسم الزبون')),
                ('customer_address', models.CharField(max_length=100, verbose_name='Customer Address   عنوان العميل')),
                ('customer_city', models.CharField(max_length=100, verbose_name='Customer City    مدينة العميل')),
                ('customer_contact_name', models.CharField(max_length=100, verbose_name='Customer Contact Name   اسم جهة اتصال العميل')),
                ('customer_contact_tel', models.CharField(max_length=100, verbose_name='Customer Contact Telephone   هاتف جهة اتصال العملاء')),
                ('customer_postal_code', models.CharField(max_length=100, verbose_name='Customer Postal Code   الرمز البريدي للعميل')),
                ('customer_vat_number', models.CharField(max_length=100, verbose_name='Customer VAT Number   رقم ضريبة القيمة المضافة للعميل')),
                ('seller_id', models.CharField(max_length=100, verbose_name='Seller ID    معرف البائع')),
                ('seller_name', models.CharField(max_length=100, verbose_name='Seller Name    البائع اسم')),
                ('seller_address', models.CharField(max_length=100, verbose_name='Seller Address    عنوان البائع')),
                ('seller_city', models.CharField(max_length=100, verbose_name='Seller City    مدينة البائع')),
                ('seller_contact_name', models.CharField(max_length=100, verbose_name='Seller Contact Name    اسم جهة اتصال البائع')),
                ('seller_contact_tel', models.CharField(max_length=100, verbose_name='Seller Contact Telephone    هاتف الاتصال بالبائع')),
                ('seller_postal_code', models.CharField(max_length=100, verbose_name='Seller Postal Code   رمز البائع البريدي')),
                ('seller_vat_number', models.CharField(max_length=100, verbose_name='Seller VAT Number   رقم ضريبة القيمة المضافة للبائع')),
                ('seller_IBAN', models.CharField(max_length=100, verbose_name='Seller IBAN Number   رقم IBAN للبائع')),
                ('vehicle_make', models.CharField(max_length=100, verbose_name='Vehicle Make   صناعة المركبات')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Vehicle Model   طراز السيارة')),
                ('vehicle_model_year', models.CharField(max_length=100, verbose_name='Vehicle Model Year   سنة صنع السيارة')),
                ('vehicle_plate_info', models.CharField(max_length=100, verbose_name='Vehicle Plate Information   معلومات لوحة المركبة')),
                ('vehicle_vin', models.CharField(max_length=100, verbose_name='Vehicle VIN Number   رقم VIN للمركبة')),
                ('claim_number', models.CharField(max_length=100, verbose_name='Claim Number   رقم المطالبة')),
                ('insurance_name', models.CharField(max_length=100, verbose_name='Insurance Name   اسم التأمين')),
                ('assessor_name', models.CharField(max_length=100, verbose_name='Assessor Name   اسم المقيم')),
                ('line_item', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='line_items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=100, verbose_name='Item Code   رمز الصنف')),
                ('item_name', models.CharField(blank=True, max_length=100, verbose_name='Item Name   اسم العنصر')),
                ('pack', models.CharField(blank=True, max_length=100, verbose_name='Pack   رزمة')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='Quantity   كمية')),
                ('unit_price', models.CharField(blank=True, max_length=100, verbose_name='Unit Price   سعر الوحدة')),
                ('taxable_amount', models.CharField(blank=True, max_length=100, verbose_name='Taxable Amount   المبلغ الخاضع للضريبة')),
                ('discount', models.CharField(blank=True, max_length=100, verbose_name='Discount   تخفيض')),
                ('tax_rate', models.CharField(blank=True, max_length=100, verbose_name='Tax Rate   معدل الضريبة')),
                ('tax_amount', models.CharField(blank=True, max_length=100, verbose_name='Tax Amount   قيمة الضريبة')),
                ('item_sub_total_including_vat', models.CharField(blank=True, max_length=100, verbose_name='Item Subtotal Including VAT   إجمالي البند بما في ذلك ضريبة القيمة المضافة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.invoice_data')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='L2',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('license_key', models.CharField(max_length=5000)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item_cal',
            fields=[
                ('cal_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_excluding_vat', models.CharField(blank=True, max_length=100, verbose_name='Total Excluding VAT   الإجمالي باستثناء ضريبة القيمة المضافة')),
                ('total_discount', models.CharField(blank=True, max_length=100, verbose_name='Total Discount   إجمالي الخصم')),
                ('total_taxable_amount_excluding_vat', models.CharField(blank=True, max_length=100, verbose_name='Total Taxable Amount Excluding VAT   إجمالي المبلغ الخاضع للضريبة  باستثناء الضريبة على القيمة المضافة')),
                ('net_excluding_VAT', models.CharField(blank=True, max_length=100, verbose_name='Net Excluding VAT   صافي باستثناء ضريبة القيمة المضافة')),
                ('total_vat_15perc', models.CharField(blank=True, max_length=100, verbose_name='Total VAT 15%   إجمالي ضريبة القيمة المضافة 15٪')),
                ('net_amount', models.CharField(blank=True, max_length=100, verbose_name='Net Amount   كمية الشبكة')),
                ('excess_amount_plus_VAT', models.CharField(blank=True, max_length=100, verbose_name='Excess Amount + VAT   المبلغ الزائد + ضريبة القيمة المضافة')),
                ('deprecation_amount_plus_VAT', models.CharField(blank=True, max_length=100, verbose_name='Deprecation Amount + VAT   مبلغ الإيقاف + ضريبة القيمة المضافة')),
                ('total_amount_due', models.CharField(blank=True, max_length=100, verbose_name='Total Amount Due   إجمالي المبلغ المستحق')),
                ('remarks', models.CharField(blank=True, max_length=100, verbose_name='Remarks   ملاحظات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.invoice_data')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='files2',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(blank=True, upload_to='pdf_files/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.invoice_data')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.invoice_data')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
